-- Footy production schema for the shared Supabase project.
-- Existing VehiclePlug tables are left untouched.
-- Footy uses isolated footy_* tables with RLS and server-only grants.

create table if not exists public.footy_data_sources (
  id bigint generated always as identity primary key,
  source_name text not null,
  source_url text,
  source_version text,
  retrieved_at timestamptz not null default now()
);

create table if not exists public.footy_matches (
  match_id text primary key,
  league text not null,
  season text not null,
  kickoff_at timestamptz,
  home_team text not null,
  away_team text not null,
  status text,
  source text not null,
  retrieved_at timestamptz not null default now()
);

create index if not exists idx_footy_matches_league_season_kickoff
  on public.footy_matches(league, season, kickoff_at);

create table if not exists public.footy_match_team_metrics (
  id bigint generated always as identity primary key,
  match_id text not null references public.footy_matches(match_id) on delete cascade,
  team text not null,
  opponent text not null,
  home_away text not null check (home_away in ('H','A')),
  goals double precision,
  goals_conceded double precision,
  xg double precision,
  npxg double precision,
  xga double precision,
  npxga double precision,
  shots double precision,
  shots_on_target double precision,
  shots_conceded double precision,
  sot_conceded double precision,
  big_chances double precision,
  big_chances_conceded double precision,
  box_touches double precision,
  key_passes double precision,
  xa double precision,
  set_piece_xg double precision,
  set_piece_xga double precision,
  possession double precision,
  ppda double precision,
  field_tilt double precision,
  deep_completions double precision,
  crosses double precision,
  shots_inside_box double precision,
  xgot double precision,
  source text not null,
  verified boolean not null default false,
  verification_status text not null default 'UNVERIFIED'
    check (verification_status in ('UNVERIFIED','PASS','WARN','BLOCKED')),
  verified_at timestamptz,
  retrieved_at timestamptz not null default now(),
  unique (match_id, team, source)
);

create index if not exists idx_footy_metrics_team
  on public.footy_match_team_metrics(team);

create index if not exists idx_footy_metrics_match
  on public.footy_match_team_metrics(match_id);

create table if not exists public.footy_data_quality_runs (
  id bigint generated by default as identity primary key,
  source text not null,
  league text not null,
  season text not null,
  status text not null check (status in ('PASS','WARN','BLOCKED')),
  report jsonb not null default '{}'::jsonb,
  checked_at timestamptz not null default now()
);

create index if not exists idx_footy_data_quality_source_checked
  on public.footy_data_quality_runs(source, league, season, checked_at desc);

alter table public.footy_data_quality_runs enable row level security;
revoke all on table public.footy_data_quality_runs from public, anon, authenticated;
grant select, insert, update, delete on table public.footy_data_quality_runs to service_role;

create table if not exists public.footy_team_ratings (
  id bigint generated always as identity primary key,
  team text not null,
  rating_type text not null,
  rating_value double precision not null,
  rating_date date not null,
  source text not null,
  unique (team, rating_type, rating_date, source)
);

create table if not exists public.footy_bookmaker_prices (
  id bigint generated always as identity primary key,
  price_key text not null unique,
  match_id text not null references public.footy_matches(match_id) on delete cascade,
  bookmaker text not null,
  market text not null,
  selection text not null,
  line double precision,
  decimal_odds double precision not null check (decimal_odds > 1.0),
  price_kind text not null default 'snapshot'
    check (price_kind in ('open', 'close', 'snapshot')),
  source text not null default 'manual',
  captured_at timestamptz not null default now()
);

create index if not exists idx_footy_prices_match_market
  on public.footy_bookmaker_prices(match_id, market, selection, captured_at desc);

drop index if exists public.uq_footy_price_snapshot;
create unique index uq_footy_price_snapshot
  on public.footy_bookmaker_prices(
    match_id,
    bookmaker,
    market,
    selection,
    coalesce(line, -9999.0),
    price_kind,
    source,
    captured_at
  );

create table if not exists public.footy_model_outputs (
  id bigint generated always as identity primary key,
  match_id text not null references public.footy_matches(match_id) on delete cascade,
  model_version text not null,
  home_xg double precision not null check (home_xg >= 0),
  away_xg double precision not null check (away_xg >= 0),
  market text not null,
  selection text not null,
  model_probability double precision check (
    model_probability is null or (model_probability >= 0 and model_probability <= 1)
  ),
  fair_odds double precision not null check (fair_odds >= 1.0),
  uncertainty_haircut double precision not null check (
    uncertainty_haircut >= 0 and uncertainty_haircut < 1
  ),
  minimum_take_price double precision not null check (minimum_take_price >= 1.0),
  created_at timestamptz not null default now()
);

create index if not exists idx_footy_model_outputs_match
  on public.footy_model_outputs(match_id);

create index if not exists idx_footy_model_outputs_model_match_created
  on public.footy_model_outputs(model_version, match_id, created_at desc);

alter table public.footy_data_sources enable row level security;
alter table public.footy_matches enable row level security;
alter table public.footy_match_team_metrics enable row level security;
alter table public.footy_team_ratings enable row level security;
alter table public.footy_bookmaker_prices enable row level security;
alter table public.footy_model_outputs enable row level security;

revoke all on table public.footy_data_sources from public, anon, authenticated;
revoke all on table public.footy_matches from public, anon, authenticated;
revoke all on table public.footy_match_team_metrics from public, anon, authenticated;
revoke all on table public.footy_team_ratings from public, anon, authenticated;
revoke all on table public.footy_bookmaker_prices from public, anon, authenticated;
revoke all on table public.footy_model_outputs from public, anon, authenticated;

grant select, insert, update, delete on table public.footy_data_sources to service_role;
grant select, insert, update, delete on table public.footy_matches to service_role;
grant select, insert, update, delete on table public.footy_match_team_metrics to service_role;
grant select, insert, update, delete on table public.footy_team_ratings to service_role;
grant select, insert, update, delete on table public.footy_bookmaker_prices to service_role;
grant select, insert, update, delete on table public.footy_model_outputs to service_role;

revoke all on sequence public.footy_data_sources_id_seq from public, anon, authenticated;
revoke all on sequence public.footy_match_team_metrics_id_seq from public, anon, authenticated;
revoke all on sequence public.footy_team_ratings_id_seq from public, anon, authenticated;
revoke all on sequence public.footy_bookmaker_prices_id_seq from public, anon, authenticated;
revoke all on sequence public.footy_model_outputs_id_seq from public, anon, authenticated;

grant usage, select on sequence public.footy_data_sources_id_seq to service_role;
grant usage, select on sequence public.footy_match_team_metrics_id_seq to service_role;
grant usage, select on sequence public.footy_team_ratings_id_seq to service_role;
grant usage, select on sequence public.footy_bookmaker_prices_id_seq to service_role;
grant usage, select on sequence public.footy_model_outputs_id_seq to service_role;


create table if not exists public.footy_backtest_runs (
  id bigint generated always as identity primary key,
  model_version text not null,
  league text not null,
  seasons text[] not null,
  prediction_rows integer not null check (prediction_rows >= 0),
  home_win_brier double precision,
  home_win_log_loss double precision,
  over_2_5_brier double precision,
  over_2_5_log_loss double precision,
  btts_brier double precision,
  btts_log_loss double precision,
  result_1x2_log_loss double precision,
  calibration jsonb,
  created_at timestamptz not null default now()
);

alter table public.footy_backtest_runs enable row level security;
revoke all on table public.footy_backtest_runs from public, anon, authenticated;
grant select, insert, update, delete on table public.footy_backtest_runs to service_role;
revoke all on sequence public.footy_backtest_runs_id_seq from public, anon, authenticated;
grant usage, select on sequence public.footy_backtest_runs_id_seq to service_role;


create table if not exists public.footy_historical_predictions (
  id bigint generated always as identity primary key,
  match_id text not null references public.footy_matches(match_id) on delete cascade,
  model_version text not null,
  model_home_xg double precision not null check (model_home_xg >= 0),
  model_away_xg double precision not null check (model_away_xg >= 0),
  uncertainty_haircut double precision not null check (
    uncertainty_haircut >= 0 and uncertainty_haircut < 1
  ),
  home_win_probability double precision not null check (
    home_win_probability >= 0 and home_win_probability <= 1
  ),
  draw_probability double precision not null check (
    draw_probability >= 0 and draw_probability <= 1
  ),
  away_win_probability double precision not null check (
    away_win_probability >= 0 and away_win_probability <= 1
  ),
  over_2_5_probability double precision not null check (
    over_2_5_probability >= 0 and over_2_5_probability <= 1
  ),
  btts_yes_probability double precision not null check (
    btts_yes_probability >= 0 and btts_yes_probability <= 1
  ),
  home_elo double precision,
  away_elo double precision,
  created_at timestamptz not null default now(),
  unique (match_id, model_version)
);

create index if not exists idx_footy_hist_pred_model
  on public.footy_historical_predictions(model_version, match_id);

alter table public.footy_historical_predictions enable row level security;
revoke all on table public.footy_historical_predictions from public, anon, authenticated;
grant select, insert, update, delete on table public.footy_historical_predictions to service_role;
revoke all on sequence public.footy_historical_predictions_id_seq from public, anon, authenticated;
grant usage, select on sequence public.footy_historical_predictions_id_seq to service_role;


create table if not exists public.footy_value_backtest_runs (
  id bigint generated always as identity primary key,
  model_version text not null,
  bookmaker text not null,
  price_kind text not null,
  source text,
  market text not null default '1X2',
  target_ev double precision not null,
  bets integer not null check (bets >= 0),
  strike_rate double precision,
  average_odds double precision,
  roi double precision,
  average_raw_ev double precision,
  average_probability_edge double precision,
  average_market_overround double precision,
  by_selection jsonb,
  by_edge_bucket jsonb,
  created_at timestamptz not null default now()
);

alter table public.footy_value_backtest_runs enable row level security;
revoke all on table public.footy_value_backtest_runs from public, anon, authenticated;
grant select, insert, update, delete on table public.footy_value_backtest_runs to service_role;
revoke all on sequence public.footy_value_backtest_runs_id_seq from public, anon, authenticated;
grant usage, select on sequence public.footy_value_backtest_runs_id_seq to service_role;


create table if not exists public.footy_model_market_validation (
  model_version text not null,
  market text not null,
  status text not null check (
    status in ('APPROVED','WATCH','RESEARCH','PASS')
  ),
  sample_size integer not null check (sample_size >= 0),
  model_log_loss double precision,
  benchmark_log_loss double precision,
  close_roi double precision,
  clv_proxy double precision,
  bookmaker_reference text,
  notes text,
  evaluated_at timestamptz not null default now(),
  primary key (model_version, market)
);

alter table public.footy_model_market_validation enable row level security;
revoke all on table public.footy_model_market_validation
  from public, anon, authenticated;
grant select, insert, update, delete
  on table public.footy_model_market_validation to service_role;


create table if not exists public.footy_strategy_rules (
  strategy_id text primary key,
  model_version text not null,
  market text not null,
  selection text not null,
  status text not null check (
    status in ('APPROVED','WATCH','RESEARCH','PASS')
  ),
  target_ev double precision not null default 0.02,
  min_probability_edge double precision,
  min_model_probability double precision,
  max_decimal_odds double precision,
  min_raw_ev double precision,
  training_seasons text[],
  holdout_seasons text[],
  training_bets integer,
  training_roi double precision,
  holdout_bets integer,
  holdout_roi double precision,
  notes text,
  evaluated_at timestamptz not null default now()
);

alter table public.footy_strategy_rules enable row level security;
revoke all on table public.footy_strategy_rules
  from public, anon, authenticated;
grant select, insert, update, delete
  on table public.footy_strategy_rules to service_role;


create table if not exists public.footy_fpl_snapshots (
  snapshot_key text primary key,
  payload jsonb not null,
  source text not null default 'fantasy.premierleague.com',
  retrieved_at timestamptz not null default now()
);

alter table public.footy_fpl_snapshots enable row level security;
revoke all on table public.footy_fpl_snapshots
  from public, anon, authenticated;
grant select, insert, update, delete
  on table public.footy_fpl_snapshots to service_role;


-- User-facing Footy information accounts.
create extension if not exists pgcrypto;

create table if not exists public.footy_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  age_confirmed_at timestamptz,
  terms_accepted_at timestamptz,
  pro_waitlist_joined_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.footy_price_alerts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  match_id text,
  event_name text not null,
  market text not null,
  selection text not null,
  bookmaker text,
  target_odds numeric(8,3) not null check (target_odds > 1),
  enabled boolean not null default true,
  last_triggered_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_footy_alerts_user_enabled
  on public.footy_price_alerts(user_id, enabled);

create table if not exists public.footy_saved_tips (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  match_id text,
  event_name text not null,
  market text not null,
  selection text not null,
  bookmaker text,
  quoted_odds numeric(8,3) check (quoted_odds is null or quoted_odds > 1),
  model_version text,
  model_probability numeric(7,6)
    check (model_probability is null or (model_probability > 0 and model_probability < 1)),
  fair_odds numeric(8,3) check (fair_odds is null or fair_odds > 1),
  minimum_take_price numeric(8,3)
    check (minimum_take_price is null or minimum_take_price > 1),
  validation_status text
    check (validation_status is null or validation_status in ('APPROVED','WATCH','RESEARCH','PASS')),
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_footy_saved_tips_user_created
  on public.footy_saved_tips(user_id, created_at desc);

create table if not exists public.footy_entitlements (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan text not null default 'FREE' check (plan in ('FREE','PRO')),
  status text not null default 'ACTIVE'
    check (status in ('ACTIVE','TRIALING','PAST_DUE','CANCELLED')),
  billing_provider text,
  external_customer_id text,
  current_period_end timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.footy_profiles enable row level security;
alter table public.footy_price_alerts enable row level security;
alter table public.footy_saved_tips enable row level security;
alter table public.footy_entitlements enable row level security;

revoke all on table public.footy_profiles, public.footy_price_alerts,
  public.footy_saved_tips, public.footy_entitlements from public, anon;

grant select, update on table public.footy_profiles to authenticated;
grant select, insert, update, delete on table public.footy_price_alerts to authenticated;
grant select, insert, update, delete on table public.footy_saved_tips to authenticated;
grant select on table public.footy_entitlements to authenticated;

grant select, insert, update, delete on table public.footy_profiles,
  public.footy_price_alerts, public.footy_saved_tips,
  public.footy_entitlements to service_role;

drop policy if exists "profiles_select_own" on public.footy_profiles;
create policy "profiles_select_own" on public.footy_profiles
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "profiles_update_own" on public.footy_profiles;
create policy "profiles_update_own" on public.footy_profiles
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "alerts_select_own" on public.footy_price_alerts;
create policy "alerts_select_own" on public.footy_price_alerts
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "alerts_insert_own" on public.footy_price_alerts;
create policy "alerts_insert_own" on public.footy_price_alerts
  for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "alerts_update_own" on public.footy_price_alerts;
create policy "alerts_update_own" on public.footy_price_alerts
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "alerts_delete_own" on public.footy_price_alerts;
create policy "alerts_delete_own" on public.footy_price_alerts
  for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "saved_tips_select_own" on public.footy_saved_tips;
create policy "saved_tips_select_own" on public.footy_saved_tips
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "saved_tips_insert_own" on public.footy_saved_tips;
create policy "saved_tips_insert_own" on public.footy_saved_tips
  for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "saved_tips_update_own" on public.footy_saved_tips;
create policy "saved_tips_update_own" on public.footy_saved_tips
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "saved_tips_delete_own" on public.footy_saved_tips;
create policy "saved_tips_delete_own" on public.footy_saved_tips
  for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "entitlements_select_own" on public.footy_entitlements;
create policy "entitlements_select_own" on public.footy_entitlements
  for select to authenticated using ((select auth.uid()) = user_id);

create or replace function public.footy_handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.footy_profiles (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  insert into public.footy_entitlements (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

revoke all on function public.footy_handle_new_user()
  from public, anon, authenticated;
grant execute on function public.footy_handle_new_user() to postgres;

drop trigger if exists on_footy_auth_user_created on auth.users;
create trigger on_footy_auth_user_created
  after insert on auth.users
  for each row execute procedure public.footy_handle_new_user();


-- Immutable public model/tip results ledger.
create table if not exists public.footy_public_calls (
  id uuid primary key default gen_random_uuid(),
  call_key text not null unique,
  source_kind text not null default 'MODEL_CALL'
    check (source_kind in ('MODEL_CALL','VALUE_TIP')),
  match_id text not null,
  model_version text not null,
  market text not null,
  selection text not null,
  model_probability double precision not null,
  fair_odds double precision not null,
  minimum_take_price double precision,
  validation_status text
    check (validation_status is null or validation_status in ('APPROVED','WATCH','RESEARCH','PASS')),
  home_team text not null,
  away_team text not null,
  kickoff_at timestamptz not null,
  published_at timestamptz not null default now(),
  quoted_bookmaker text,
  quoted_odds double precision check (quoted_odds is null or quoted_odds > 1),
  price_captured_at timestamptz,
  closing_odds double precision check (closing_odds is null or closing_odds > 1),
  home_goals integer,
  away_goals integer,
  result_status text not null default 'OPEN'
    check (result_status in ('OPEN','WON','LOST','PUSH','VOID')),
  unit_profit double precision,
  clv double precision,
  settled_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_footy_public_calls_kickoff
  on public.footy_public_calls(kickoff_at desc);
create index if not exists idx_footy_public_calls_status
  on public.footy_public_calls(result_status, kickoff_at desc);

alter table public.footy_public_calls enable row level security;
revoke all on table public.footy_public_calls from public, anon, authenticated;
grant select, insert, update, delete
  on table public.footy_public_calls to service_role;


-- Live UK bookmaker odds cache and alert events.
create table if not exists public.footy_live_odds_current (
  price_key text primary key,
  provider text not null,
  provider_event_id text not null,
  match_id text,
  sport_key text not null,
  home_team text not null,
  away_team text not null,
  commence_time timestamptz not null,
  bookmaker_key text not null,
  bookmaker_name text not null,
  market text not null,
  selection text not null,
  line double precision,
  decimal_odds double precision not null check (decimal_odds > 1),
  previous_decimal_odds double precision
    check (previous_decimal_odds is null or previous_decimal_odds > 1),
  provider_last_update timestamptz,
  captured_at timestamptz not null default now()
);

create index if not exists idx_footy_live_odds_match
  on public.footy_live_odds_current(match_id, market, selection);
create index if not exists idx_footy_live_odds_event
  on public.footy_live_odds_current(provider_event_id, bookmaker_key, market);

create table if not exists public.footy_live_odds_history (
  id bigint generated by default as identity primary key,
  price_key text not null,
  provider text not null,
  provider_event_id text not null,
  match_id text,
  bookmaker_key text not null,
  bookmaker_name text not null,
  market text not null,
  selection text not null,
  line double precision,
  decimal_odds double precision not null check (decimal_odds > 1),
  captured_at timestamptz not null default now()
);

create index if not exists idx_footy_live_odds_history_match
  on public.footy_live_odds_history(match_id, captured_at desc);

create table if not exists public.footy_odds_feed_status (
  provider text primary key,
  sport_key text not null,
  last_success_at timestamptz,
  last_attempt_at timestamptz,
  credits_remaining integer,
  credits_used integer,
  last_request_cost integer,
  events_received integer,
  prices_received integer,
  last_error text,
  updated_at timestamptz not null default now()
);

create table if not exists public.footy_alert_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  alert_id uuid not null references public.footy_price_alerts(id) on delete cascade,
  match_id text,
  event_name text not null,
  market text not null,
  selection text not null,
  bookmaker text,
  target_odds double precision not null check (target_odds > 1),
  observed_odds double precision not null check (observed_odds > 1),
  triggered_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists idx_footy_alert_events_user
  on public.footy_alert_events(user_id, triggered_at desc);

alter table public.footy_price_alerts
  add column if not exists was_above_target boolean not null default false,
  add column if not exists last_observed_odds double precision,
  add column if not exists last_checked_at timestamptz;

alter table public.footy_live_odds_current enable row level security;
alter table public.footy_live_odds_history enable row level security;
alter table public.footy_odds_feed_status enable row level security;
alter table public.footy_alert_events enable row level security;

revoke all on table public.footy_live_odds_current,
  public.footy_live_odds_history, public.footy_odds_feed_status
  from public, anon, authenticated;
grant select, insert, update, delete on table public.footy_live_odds_current,
  public.footy_live_odds_history, public.footy_odds_feed_status
  to service_role;

revoke all on table public.footy_alert_events from public, anon;
grant select, update on table public.footy_alert_events to authenticated;
grant select, insert, update, delete on table public.footy_alert_events
  to service_role;

drop policy if exists "alert_events_select_own"
  on public.footy_alert_events;
create policy "alert_events_select_own"
  on public.footy_alert_events
  for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "alert_events_update_own"
  on public.footy_alert_events;
create policy "alert_events_update_own"
  on public.footy_alert_events
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);


-- Footy League Edge: automated mini-league product.
create table if not exists public.footy_fpl_leagues (
  league_id bigint primary key,
  league_name text,
  last_synced_at timestamptz,
  last_deep_synced_at timestamptz,
  current_event integer,
  sync_status text not null default 'PENDING'
    check (sync_status in ('PENDING','SYNCING','READY','ERROR')),
  last_error text,
  connect_count integer not null default 1,
  first_connected_at timestamptz not null default now(),
  last_connected_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.footy_fpl_league_entries (
  league_id bigint not null references public.footy_fpl_leagues(league_id) on delete cascade,
  entry_id bigint not null,
  entry_name text not null,
  player_name text,
  rank integer,
  last_rank integer,
  event_total integer,
  total integer,
  synced_at timestamptz not null default now(),
  primary key (league_id, entry_id)
);

create index if not exists idx_footy_fpl_league_entries_rank
  on public.footy_fpl_league_entries(league_id, rank);

create table if not exists public.footy_fpl_entry_snapshots (
  league_id bigint not null references public.footy_fpl_leagues(league_id) on delete cascade,
  entry_id bigint not null,
  event integer not null,
  picks jsonb not null default '[]'::jsonb,
  active_chip text,
  automatic_subs jsonb not null default '[]'::jsonb,
  entry_history jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now(),
  primary key (league_id, entry_id, event)
);

create table if not exists public.footy_fpl_league_recaps (
  league_id bigint not null references public.footy_fpl_leagues(league_id) on delete cascade,
  event integer not null,
  facts jsonb not null,
  recap_copy text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (league_id, event)
);

create table if not exists public.footy_fpl_receipts (
  league_id bigint not null references public.footy_fpl_leagues(league_id) on delete cascade,
  event integer not null,
  frozen_at timestamptz not null,
  probabilities jsonb not null,
  top_moves jsonb not null default '{}'::jsonb,
  outcome jsonb,
  scored_at timestamptz,
  created_at timestamptz not null default now(),
  primary key (league_id, event)
);

alter table public.footy_fpl_leagues enable row level security;
alter table public.footy_fpl_league_entries enable row level security;
alter table public.footy_fpl_entry_snapshots enable row level security;
alter table public.footy_fpl_league_recaps enable row level security;
alter table public.footy_fpl_receipts enable row level security;

revoke all on table public.footy_fpl_leagues,
  public.footy_fpl_league_entries,
  public.footy_fpl_entry_snapshots,
  public.footy_fpl_league_recaps,
  public.footy_fpl_receipts
from public, anon, authenticated;

grant select, insert, update, delete on table public.footy_fpl_leagues,
  public.footy_fpl_league_entries,
  public.footy_fpl_entry_snapshots,
  public.footy_fpl_league_recaps,
  public.footy_fpl_receipts
to service_role;


create table if not exists public.footy_fpl_events (
  id bigint generated by default as identity primary key,
  session_key text,
  league_id bigint,
  event_name text not null,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_footy_fpl_events_name_created
  on public.footy_fpl_events(event_name, created_at desc);

alter table public.footy_fpl_events enable row level security;
revoke all on table public.footy_fpl_events from public, anon, authenticated;
grant select, insert, update, delete on table public.footy_fpl_events to service_role;


-- League Edge recommendation snapshots: append-only inputs for Receipts.
create table if not exists public.footy_fpl_recommendation_snapshots (
  id uuid primary key default gen_random_uuid(),
  league_id bigint not null references public.footy_fpl_leagues(league_id) on delete cascade,
  entry_id bigint not null,
  rival_entry_id bigint,
  event integer not null,
  deadline_time timestamptz not null,
  generated_at timestamptz not null default now(),
  data_retrieved_at timestamptz not null,
  model_version text not null default 'league-edge-v1',
  battle_mode text not null check (battle_mode in ('PROTECT','CHASE','RECOVER')),
  captain_options jsonb not null default '[]'::jsonb,
  transfer_options jsonb not null default '[]'::jsonb,
  overlap jsonb not null default '{}'::jsonb,
  player_trends jsonb not null default '[]'::jsonb,
  team_trends jsonb not null default '[]'::jsonb,
  is_pre_deadline boolean not null default true,
  actual_captain_id bigint,
  actual_incoming_ids jsonb,
  matched_top3 boolean,
  matched_captain_top3 boolean,
  matched_transfer_top3 boolean,
  scored_at timestamptz
);

create index if not exists idx_footy_fpl_reco_entry_event
  on public.footy_fpl_recommendation_snapshots(league_id, entry_id, event, generated_at desc);
create index if not exists idx_footy_fpl_reco_deadline
  on public.footy_fpl_recommendation_snapshots(deadline_time, generated_at desc);

alter table public.footy_fpl_recommendation_snapshots enable row level security;
revoke all on table public.footy_fpl_recommendation_snapshots from public, anon, authenticated;
grant select, insert, update, delete on table public.footy_fpl_recommendation_snapshots to service_role;


-- Private Footy owner/admin access. Server/service-role only.
create table if not exists public.footy_admin_credentials (
  id text primary key,
  key_hash text not null,
  label text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.footy_admin_sessions (
  token_hash text primary key,
  credential_id text not null references public.footy_admin_credentials(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

alter table public.footy_admin_credentials enable row level security;
alter table public.footy_admin_sessions enable row level security;

revoke all on table public.footy_admin_credentials from public, anon, authenticated;
revoke all on table public.footy_admin_sessions from public, anon, authenticated;
grant select, insert, update, delete on table public.footy_admin_credentials to service_role;
grant select, insert, update, delete on table public.footy_admin_sessions to service_role;

create index if not exists idx_footy_admin_sessions_credential
  on public.footy_admin_sessions(credential_id);


-- Player-process and territory enrichment.
alter table public.footy_match_team_metrics
  add column if not exists final_third_passes double precision,
  add column if not exists opposition_half_passes double precision,
  add column if not exists territory_proxy double precision
    check (territory_proxy is null or (territory_proxy >= 0 and territory_proxy <= 100)),
  add column if not exists xgot_faced double precision,
  add column if not exists goals_prevented double precision;

create table if not exists public.footy_player_match_metrics (
  id bigint generated always as identity primary key,
  season text not null,
  gameweek integer,
  competition text not null,
  provider_match_id text not null,
  footy_match_id text references public.footy_matches(match_id) on delete set null,
  kickoff_at timestamptz,
  player_id integer not null,
  player_code bigint,
  player_name text,
  team text not null,
  opponent text,
  minutes double precision,
  goals double precision,
  assists double precision,
  shots double precision,
  shots_on_target double precision,
  xg double precision,
  npxg double precision,
  penalties_scored double precision,
  penalties_missed double precision,
  penalty_xg_value double precision,
  xa double precision,
  xgot double precision,
  big_chances_missed double precision,
  touches double precision,
  box_touches double precision,
  chances_created double precision,
  final_third_passes double precision,
  accurate_crosses double precision,
  interceptions double precision,
  recoveries double precision,
  blocks double precision,
  clearances double precision,
  headed_clearances double precision,
  duels_won double precision,
  duels_lost double precision,
  was_fouled double precision,
  fouls_committed double precision,
  saves double precision,
  goals_conceded double precision,
  xgot_faced double precision,
  goals_prevented double precision,
  sweeper_actions double precision,
  high_claims double precision,
  saves_inside_box double precision,
  defensive_contributions double precision,
  source text not null,
  verified boolean not null default false,
  verification_status text not null default 'UNVERIFIED'
    check (verification_status in ('UNVERIFIED','PASS','WARN','BLOCKED')),
  verified_at timestamptz,
  retrieved_at timestamptz not null default now(),
  unique (provider_match_id, player_id, source)
);

alter table public.footy_player_match_metrics
  add column if not exists npxg double precision,
  add column if not exists penalties_scored double precision,
  add column if not exists penalties_missed double precision,
  add column if not exists penalty_xg_value double precision;

create index if not exists idx_footy_player_metrics_player_kickoff
  on public.footy_player_match_metrics(player_id, kickoff_at desc);
create index if not exists idx_footy_player_metrics_player_code_kickoff
  on public.footy_player_match_metrics(player_code, kickoff_at desc);
create index if not exists idx_footy_player_metrics_team_kickoff
  on public.footy_player_match_metrics(team, kickoff_at desc);
create index if not exists idx_footy_player_metrics_competition
  on public.footy_player_match_metrics(competition, kickoff_at desc);
create index if not exists idx_footy_player_metrics_footy_match
  on public.footy_player_match_metrics(footy_match_id);

alter table public.footy_player_match_metrics enable row level security;
revoke all on table public.footy_player_match_metrics from public, anon, authenticated;
grant select, insert, update, delete on table public.footy_player_match_metrics to service_role;
revoke all on sequence public.footy_player_match_metrics_id_seq from public, anon, authenticated;
grant usage, select on sequence public.footy_player_match_metrics_id_seq to service_role;


create table if not exists public.footy_player_season_priors (
  id bigint generated always as identity primary key,
  season text not null,
  player_code bigint not null,
  player_id integer,
  player_name text not null,
  position text,
  team text,
  minutes double precision not null default 0,
  starts double precision,
  total_points double precision,
  xg double precision,
  xa double precision,
  xgi double precision,
  xg_per90 double precision,
  xa_per90 double precision,
  xgi_per90 double precision,
  starts_per90 double precision,
  defensive_contributions double precision,
  defensive_contribution_per90 double precision,
  saves_per90 double precision,
  source text not null,
  verified boolean not null default false,
  verification_status text not null default 'UNVERIFIED'
    check (verification_status in ('UNVERIFIED','PASS','WARN','BLOCKED')),
  retrieved_at timestamptz not null default now(),
  unique (season, player_code, source)
);

create index if not exists idx_footy_player_priors_code_season
  on public.footy_player_season_priors(player_code, season desc);

alter table public.footy_player_season_priors enable row level security;
revoke all on table public.footy_player_season_priors from public, anon, authenticated;
grant select, insert, update, delete on table public.footy_player_season_priors to service_role;
revoke all on sequence public.footy_player_season_priors_id_seq from public, anon, authenticated;
grant usage, select on sequence public.footy_player_season_priors_id_seq to service_role;
